name       : xproto
version    : 7.0.31
release    : 7
source     :
    - https://www.x.org/releases/individual/proto/xproto-7.0.31.tar.gz : 6d755eaae27b45c5cc75529a12855fed5de5969b367ed05003944cf901ed43c7
license    :
    - MIT
summary    : X Window System Core Protocol
component  : xorg.proto
description: |
    This package provides the headers and specification documents defining the X Window System Core Protocol, Version 11. It also includes a number of headers that aren't purely protocol related, but are depended upon by many other X Window System packages to provide common definitions and porting layer.
patterns   : /
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
